### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by iwataka123** [iwataka123/furima-40007#20]
いつもお世話になっております。
アプリの挙動確認をお願い致します。

# URL
https://furima-40007.onrender.com/

# Basic認証
ID　　　：iwataka
Password：475901

# 出品者のログイン情報
アドレス：sample@sample.co.jp
Password：iwa1192

# 購入者のログイン情報
アドレス：test@sample.com
Password：test1192

何卒宜しくお願い致します。

**Comment by mo1015** [comment]
@iwataka123 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
一度出品に失敗しエラーが出た後、再度価格を入力したときに手数料と利益が表示されません。
どの段階でも表示されるよう修正しましょう。

- [x] **必要な情報を適切に入力して「変更する」ボタンを押すと、商品情報（商品画像・商品名・商品の状態など）を編集できること**
必要な情報を適切に入力して「変更する」ボタンを押しても、編集ができませんでした。

- [x] **編集ページにて、エラーハンドリングができていること（入力に問題がある状態で「変更する」ボタンが押された場合、情報は保存されず、編集ページに戻りエラーメッセージが表示されること）**
エラーメッセージが表示されませんでした。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by iwataka123** [comment]
ご確認・ご指摘ありがとうございました。

修正しましたので、再度ご確認お願い致します。

**Comment by snkw-works** [comment]
@iwataka123 さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by iwataka123** [comment]
ありがとうございます！！
皆様のおかげでたどり着くことができました！！
